# Generated by Django 3.1.6 on 2021-02-10 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price_multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('price_multiplier', models.FloatField(default=1.0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.scheduleday')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bought', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('prise', models.IntegerField(default=0)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.seance')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.site')),
            ],
        ),
    ]
