# Generated by Django 3.1.6 on 2021-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='prise',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='scheduleday',
            name='day',
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seance',
            name='time',
            field=models.TimeField(),
        ),
    ]
