# Generated by Django 3.1.6 on 2021-03-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20210218_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleday',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
