# Generated by Django 3.1.6 on 2021-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20210306_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='price',
            field=models.FloatField(default=100.0),
        ),
    ]
