# Generated by Django 3.1.6 on 2021-03-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_seance_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleday',
            name='slug',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
